export class LanguageConfig {
    public en: any;
    public es: any;

    constructor() {
        this.en = {
            common: {
                welcomeToApp: 'Welcome to Bitpeople!',
                chooseTfaOption: 'Chose a two-factor authentication option',
                atLeast: 'at least',
                characters: 'characters',
                accountType: 'Account type',
                register: 'Register',
                forgotPassword: 'Forgot your password?',
                facebookLogin: 'Login with Facebook',
                gmailLogin: 'Login with Gmail',
                token: 'Token',
                continue: 'Continue',
                login: 'Login',
                logout: 'Logout',
                signup: 'Sign up',
                disable: 'Disable',
                enable: 'Enable',
                loginSecurity: 'Login security',
                others: 'Others',
                acceptTerms: 'I agree to Bitpeople terms',
                registerStarted: 'Started with Bitpeople!',
                createAccount: 'Create your account',
                passwordRequest: 'New password request',
                tokenEmailSent: 'A new token has been sent to your email',
                successConfirm: 'Confirmed successfully',
                newToken: 'New token',
                changePassword: 'Change your password',
                passwordChanged: 'Password changed',
                save: 'Save',
                user: 'User',
                proof: 'Proof of address',
                checkIt: 'Check it',
                documentsReview: 'Documents review',
                decline: 'Decline',
                adminCreated: 'Admin created',
                createAdmin: 'Create new admin account',
                create: 'Create',
                contact: 'Contact',
                profession: 'Profession',
                experience: 'Experience',
                education: 'Education',
                loading: 'Loading...',
                emailSent: 'We have sent you a new email to confirm',
                recover: 'Recover',
                cancel: 'Cancel',
                close: 'Close'
            },
            buttons: {
                deleteKnowledge: 'Delete knowledge',
                deleteExperience: 'Delete experience',
                saveContinue: 'Save and continue',
                saveAdd: 'Save and add new',
            },
            menu: {
                home: 'Home',
                profile: 'Profile',
                settings: 'Settings',
                createAdmin: 'Create administrator',
                confirmUsers: 'Confirm users',
            },
            inputs: {
                email: 'Email address',
                password: 'Password',
                passwordConfirm: 'Password confirm',
                captchaConfirm: 'Captcha confirm',
                country: 'Country',
                state: 'State',
                city: 'City',
                zipCode: 'Zip code',
                address: 'Address',
                gender: 'Gender',
                name: 'Name',
                birthdate: 'Birthdate',
                domicile: 'Search domicile',
                phone: 'Phone',
                idfront: 'Identification (Front face)',
                idback: 'Identification (Back face)',
                proof: 'Proof of address',
                numExt: 'Outside number',
                numInt: 'Interior number',
                suburb: 'Suburb',
                street: 'Street',
                surname: 'Surname',
                lastName: 'Last name',
                jobTitle: 'Job title',
                expectedSalary: 'Expected salary',
                knowledge: 'Knowledge',
                levelExperience: 'Level of experience',
                yearsExperience: 'Years of experience',
                other: 'Other',
                firstJob: 'I am looking for my first job',
                jobPosition: 'Profession',
                company: 'Company',
                description: 'Description',
                startDate: 'Start date',
                endDate: 'End date',
                stillWorking: 'Still working here',
                schoolInstitution: 'School institution',
                studyLevel: 'Study level',
                career: 'Career',
                stillStudying: 'Still studying',
                errors: {
                    required: 'Required field',
                    format: 'Invalid format',
                    length: 'Length must be',
                    passwordMatch: 'Passwords must match',
                    isMajor: 'You need to be of legal age',
                    domicile: 'Enter a valid domicile',
                    unique: 'This value must be unique',
                }
            },
            tfa: {
                sendToken: 'Send a verification token to email',
                title: 'Two Factor Authentication',
                subtitle: 'Enable or disable a two-factor authentication option',
                descritpion: 'Add additional security with two-step authentication. You can active one or more options to authenticate in two steps.',
                step1: 'Provide your email and password',
                step2: 'Provide a token code, configured by an external application using a QR code or by email.',
                emailDescription: 'To access with this option, the next time you try to log in, you will be able to get a token by email.',
                emailStrongDescription: 'This option always will be available if you active any other.',
                googleDescription: 'To get a token code, download from your mobile app store Google Authenticator and scan the following QR code.',
            },
            backend: {
                errors: {
                    399: 'Something wrong',
                    452: 'Invalid email or password',
                    453: 'Invalid account type for login',
                    454: 'Invalid TFA token',
                    455: 'Invalid OAuth token',
                    456: 'This email has already been taken',
                    457: 'User not found',
                    458: 'Invalid token',
                    459: 'The token has been expired',
                }
            },
            errors: {
                declineDocuments: 'Verification of documents without success',
                declineDocumentsList: 'The following documents could not be verified: '
            },
            alerts: {
              confirmPasswordHeader: 'Confirm password',
              confirmPasswordMessage: 'Enter your password to confirm:',
              invalidPassword: 'Invalid password',
              disableFingerprintHeader: 'Disable fingerprint login',
              disableFingerprintMessage: 'Do you want to disable fingerprint login?',
              disable: 'Disable'
            },
            fingerprint: {
              enableFingerprint: 'Enable fingerprint login'
            }
        };
        this.es = {
            common: {
                welcomeToApp: '¡Bienvenido a Bitpeople!',
                chooseTfaOption: 'Selecciona opción para la autenticación en dos pasos',
                atLeast: 'al menos',
                characters: 'carácteres',
                accountType: 'Tipo de cuenta',
                register: 'Registrarse',
                forgotPassword: 'Recuperar contraseña',
                facebookLogin: 'Iniciar con Facebook',
                gmailLogin: 'Iniciar con Gmail',
                token: 'Código',
                continue: 'Continuar',
                login: 'Iniciar sesión',
                logout: 'Cerrar sesión',
                signup: 'Regístrate',
                disable: 'Habilitar',
                enable: 'Deshabilitar',
                loginSecurity: 'Seguridad de inicio de sesión',
                others: 'Otros',
                acceptTerms: 'Estoy de acuerdo con los términos de Bitpeople',
                registerStarted: 'Únete a Bitpeople',
                createAccount: 'Crea tu cuenta',
                passwordRequest: 'Solicitar nueva contraseña',
                tokenEmailSent: 'Un nuevo código de verificación ha sido enviado a tu correo',
                successConfirm: 'Confirmado correctamente',
                newToken: 'Nuevo código de verificación',
                changePassword: 'Cambiar contraseña',
                passwordChanged: 'Contraseña restablecida',
                save: 'Guardar',
                user: 'Usuario',
                proof: 'Comprobante de domicilio',
                checkIt: 'Revizar',
                documentsReview: 'Revisión de documentos',
                decline: 'Rechazar',
                adminCreated: 'Administrador creado',
                createAdmin: 'Crear cuenta de administrador',
                create: 'Crear',
                contact: 'Contacto',
                profession: 'Profesión',
                experience: 'Experiencia',
                education: 'Educación',
                loading: 'Cargando...',
                emailSent: 'Te hemos enviado un nuevo correo electrónico para confirmar',
                recover: 'Recuperar',
                cancel: 'Cancelar',
                close: 'Cerrar'
            },
            buttons: {
                deleteKnowledge: 'Eliminar conocimiento',
                deleteExperience: 'Eliminar experiencia',
                saveContinue: 'Guardar y continuar',
                saveAdd: 'Guardar y agregar nuevo',
            },
            menu: {
                home: 'Inicio',
                profile: 'Perfil',
                settings: 'Configuración',
                createAdmin: 'Crear administrador',
                confirmUsers: 'Confirmar usuarios',
            },
            inputs: {
                email: 'Correo',
                password: 'Contraseña',
                passwordConfirm: 'Confirma la contraseña',
                captchaConfirm: 'Realiza el captcha',
                country: 'País',
                state: 'Estado',
                city: 'Ciudad',
                zipCode: 'Código postal',
                address: 'Domicilio',
                gender: 'Género',
                name: 'Nombre',
                birthdate: 'Fecha de nacimiento',
                domicile: 'Buscar domicilio',
                phone: 'Phone',
                idfront: 'Identificación (Cara frontal)',
                idback: 'Identificación (Cara del reverso)',
                proof: 'Comprobante de domicilio',
                numExt: 'Numero exterior',
                numInt: 'Numero interior',
                suburb: 'Suburb',
                street: 'Street',
                surname: 'Primer apellido',
                lastName: 'Segundo apellido',
                jobTitle: 'Título profesional',
                expectedSalary: 'Salario esperado',
                knowledge: 'Conocimiento',
                levelExperience: 'Nivel de experiencia',
                yearsExperience: 'Años de experiencia',
                other: 'Otro',
                firstJob: 'Estoy en busca de mi primer empleo',
                jobPosition: 'Profesión',
                company: 'Empresa',
                description: 'Descripción',
                startDate: 'Fecha de inicio',
                endDate: 'Fecha de fin',
                stillWorking: 'Sigo trabajando aqui',
                schoolInstitution: 'Institución escolar',
                studyLevel: 'Nivel de estudio',
                career: 'Carrera',
                stillStudying: 'Sigue estudiando',
                errors: {
                    required: 'Campo requerido',
                    format: 'Formato invalido',
                    length: 'La longitud debe de ser',
                    passwordMatch: 'Las contraseñas deben coincidir',
                    isMajor: 'Necesitas ser mayor de edad',
                    domicile: 'Introduce un domicilio valido',
                    unique: 'Este valor debe ser unico',
                }
            },
            tfa: {
                sendToken: 'Enviar código de verificación al correo',
                title: 'Autenticación en dos pasos',
                subtitle: 'Habilite o deshabilite una opción de autenticación en dos pasos',
                descritpion: 'Agregue seguridad adicional con la autenticación de dos pasos. Puede activar una o más opciones para autenticarse en dos pasos.',
                step1: 'Proporciona tu correo y contraseña.',
                step2: 'Proporcione un código de verificación, configurado por una aplicación externa utilizando un código QR o por correo electrónico.',
                emailDescription: 'Para acceder con esta opción, la próxima vez que intente iniciar sesión, podrá obtener un código de verificación por correo electrónico.',
                emailStrongDescription: 'Esta opción siempre estará disponible si activa cualquier otra.',
                googleDescription: 'Para obtener un código de verificación, descargue desde su tienda de aplicaciones móviles Google Authenticator y escanee el siguiente código QR.',
            },
            backend: {
                errors: {
                    399: 'Algo salió mal',
                    452: 'Correo o contraseña invalido',
                    453: 'Tipo de cuenta invalido para iniciar',
                    454: 'Código TFA invalido',
                    455: 'Código OAuth invalido',
                    456: 'Este correo ya está en uso',
                    457: 'Usuario no encontrado',
                    458: 'Código de verificación invalido',
                    459: 'El código de verificación ha expirado'
                }
            },
            errors: {
                declineDocuments: 'Verificación de documentos sin éxito',
                declineDocumentsList: 'Los siguientes documentos no pudieron ser verificados: '
            },
            alerts: {
              confirmPasswordHeader: 'Confirmar contraseña',
              confirmPasswordMessage: 'Ingresa tu contraseña para confirmar:',
              invalidPassword: 'Contraseña incorrecta',
              disableFingerprintHeader: 'Inhabilitar huella dactilar',
              disableFingerprintMessage: '¿Quieres inhabilitar el inicio de sesión con tu huella dactilar?',
              disable: 'Inhabilitar'
            },
            fingerprint: {
              enableFingerprint: 'Inicio de sesisón con huella'
            }
        };
    }
}
